cc_library(
    name = "mpl_lib",
    # srcs = glob([
    #     "**/*.cc",
    # ]),
    hdrs = glob([
        "matplotlib/**/*.h",
    ]),
    visibility = [
        "//visibility:public"
    ],
    linkopts = [
        "-lpython"
    ],
)